# Redirige todo el tráfico HTTP a HTTPS
<VirtualHost *:80>
    ServerName glpi.empresa.local
    ServerAlias 192.168.1.171
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

# Configuración principal con HTTPS
<VirtualHost *:443>
    ServerName glpi.empresa.local
    ServerAlias 192.168.1.171
    DocumentRoot /var/www/glpi/public

    # Certificado SSL
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/glpi.crt
    SSLCertificateKeyFile /etc/ssl/private/glpi.key

    <Directory /var/www/glpi/public>
        Require all granted
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
    </Directory>

    IncludeOptional /etc/modsecurity/*.conf
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"
    SecRuleEngine On
    SecAction "id:9999,phase:1,pass,nolog,ctl:ruleRemoveById=941100-941999"
    SecRuleRemoveById 920350
    SecRuleRemoveById 920420
    SecRuleRemoveById 949110
    SecRuleRemoveById 980130
</VirtualHost>
